name: Docker

on:
  push:
  pull_request:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 0 7,22 * *'

jobs:
  Distros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [alpine, archlinux, centos, debian, fedora, opensuse, ubuntu]
        lang: [cpp, python, dotnet, java]
      fail-fast: false
    env:
      DISTRO: ${{ matrix.distro }}
      LANG: ${{ matrix.lang }}
    steps:
    - uses: actions/checkout@v2
    - name: Build base image
      run: make --directory=ci ${DISTRO}_base
    - name: Build env image
      run: make --directory=ci ${DISTRO}_${LANG}_env
    - name: Build devel project
      run: make --directory=ci ${DISTRO}_${LANG}_devel
    - name: Build project
      run: make --directory=ci ${DISTRO}_${LANG}_build
    - name: Test project
      run: make --directory=ci ${DISTRO}_${LANG}_test

    - name: Build env Install
      run: make --directory=ci ${DISTRO}_${LANG}_install_env
    - name: Build devel Install
      run: make --directory=ci ${DISTRO}_${LANG}_install_devel
    - name: Build Install
      run: make --directory=ci ${DISTRO}_${LANG}_install_build
    - name: Test Install
      run: make --directory=ci ${DISTRO}_${LANG}_install_test
